#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PocketStatistician.Resource", IsApplication=true)]

namespace PocketStatistician
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Syncfusion.Data.Resource.String.library_name = global::PocketStatistician.Resource.String.library_name;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Ascending = global::PocketStatistician.Resource.Drawable.Ascending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Descending = global::PocketStatistician.Resource.Drawable.Descending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.DragDown = global::PocketStatistician.Resource.Drawable.DragDown;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.DragUp = global::PocketStatistician.Resource.Drawable.DragUp;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.error2 = global::PocketStatistician.Resource.Drawable.error2;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.FirstPageIcon = global::PocketStatistician.Resource.Drawable.FirstPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupCollapse = global::PocketStatistician.Resource.Drawable.GroupCollapse;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupExpander = global::PocketStatistician.Resource.Drawable.GroupExpander;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.LastPageIcon = global::PocketStatistician.Resource.Drawable.LastPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.NextPageIcon = global::PocketStatistician.Resource.Drawable.NextPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.PrevPageIcon = global::PocketStatistician.Resource.Drawable.PrevPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Sort = global::PocketStatistician.Resource.Drawable.Sort;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.SortDescending = global::PocketStatistician.Resource.Drawable.SortDescending;
			global::Syncfusion.SfDataGrid.Android.Resource.Layout.ScrollViewer = global::PocketStatistician.Resource.Layout.ScrollViewer;
			global::Syncfusion.SfDataGrid.Android.Resource.String.library_name = global::PocketStatistician.Resource.String.library_name;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.Ascending = global::PocketStatistician.Resource.Drawable.Ascending;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.Descending = global::PocketStatistician.Resource.Drawable.Descending;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.DragDown = global::PocketStatistician.Resource.Drawable.DragDown;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.DragUp = global::PocketStatistician.Resource.Drawable.DragUp;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.error2 = global::PocketStatistician.Resource.Drawable.error2;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.FirstPageIcon = global::PocketStatistician.Resource.Drawable.FirstPageIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.GroupCollapse = global::PocketStatistician.Resource.Drawable.GroupCollapse;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.GroupExpander = global::PocketStatistician.Resource.Drawable.GroupExpander;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.LastPageIcon = global::PocketStatistician.Resource.Drawable.LastPageIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.NextPageIcon = global::PocketStatistician.Resource.Drawable.NextPageIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.PrevPageIcon = global::PocketStatistician.Resource.Drawable.PrevPageIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.Sort = global::PocketStatistician.Resource.Drawable.Sort;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.SortDescending = global::PocketStatistician.Resource.Drawable.SortDescending;
			global::Syncfusion.SfGridConverter.Android.Resource.Layout.ScrollViewer = global::PocketStatistician.Resource.Layout.ScrollViewer;
			global::Syncfusion.SfGridConverter.Android.Resource.String.library_name = global::PocketStatistician.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int scale_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int scale_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int anayisis_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ascending = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Descending = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int DragDown = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int DragUp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int error2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exp_to_excel = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int FirstPageIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GroupCollapse = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int GroupExpander = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int LastPageIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int NextPageIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int PrevPageIcon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int reset_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Sort = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int SortDescending = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080015
			public const int analysisSwitch = 2131230741;
			
			// aapt resource value: 0x7f080008
			public const int axisLayout = 2131230728;
			
			// aapt resource value: 0x7f080020
			public const int bottom_labels = 2131230752;
			
			// aapt resource value: 0x7f080002
			public const int chartAreaLayout = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int chartTitle = 2131230721;
			
			// aapt resource value: 0x7f080021
			public const int content = 2131230753;
			
			// aapt resource value: 0x7f080006
			public const int dataMarkerLayout = 2131230726;
			
			// aapt resource value: 0x7f080026
			public const int exportToExcel = 2131230758;
			
			// aapt resource value: 0x7f080011
			public const int fieldsLayout = 2131230737;
			
			// aapt resource value: 0x7f08001c
			public const int fieldsSize = 2131230748;
			
			// aapt resource value: 0x7f080003
			public const int gridLineLayout = 2131230723;
			
			// aapt resource value: 0x7f080022
			public const int gridLinesLayout = 2131230754;
			
			// aapt resource value: 0x7f08000d
			public const int iconView = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int label = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int legendHeader = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int legendItemsLayout = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int legendScrollView = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int legendViewGroup = 2131230729;
			
			// aapt resource value: 0x7f08001e
			public const int linLay = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int nextBT = 2131230749;
			
			// aapt resource value: 0x7f080016
			public const int optionalQuestionLayout = 2131230742;
			
			// aapt resource value: 0x7f080012
			public const int procDataBT = 2131230738;
			
			// aapt resource value: 0x7f080018
			public const int radioGroup1 = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int rb1 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int rb2 = 2131230746;
			
			// aapt resource value: 0x7f080027
			public const int resetBT = 2131230759;
			
			// aapt resource value: 0x7f080000
			public const int rootLayout = 2131230720;
			
			// aapt resource value: 0x7f080025
			public const int sample_content_fragment = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int sample_main_layout = 2131230756;
			
			// aapt resource value: 0x7f080010
			public const int scrollView1 = 2131230736;
			
			// aapt resource value: 0x7f080005
			public const int seriesLayout = 2131230725;
			
			// aapt resource value: 0x7f080013
			public const int sliding_tabs = 2131230739;
			
			// aapt resource value: 0x7f080004
			public const int stripLinesLayout = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int technicalIndicatorLayout = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int textView1 = 2131230735;
			
			// aapt resource value: 0x7f08001b
			public const int textView2 = 2131230747;
			
			// aapt resource value: 0x7f080017
			public const int textView3 = 2131230743;
			
			// aapt resource value: 0x7f080023
			public const int thumbLayout = 2131230755;
			
			// aapt resource value: 0x7f08001f
			public const int top_labels = 2131230751;
			
			// aapt resource value: 0x7f080014
			public const int viewpager = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chart_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_legend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExcerptFieldsLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_sample = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int pager_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int range_navigator_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ResultLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ScrollViewer = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionBarIcons = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000a
			public const int ApplicationName = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int Hello = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int analysis_prompt = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int q = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int quarter = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int sfchart_close_label = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sfchart_high_label = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int sfchart_low_label = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int sfchart_open_label = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int w = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int week = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
